config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get 'archive' => 'static_pages#archive'


  
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def archive
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title = '')
		base_title = "J and J Capitol Enterprises | Oil and Fuel Additives"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>

	<ul class="center inline">
		<li class="active"><%= link_to "Home",     root_path    %></li>
		<li><%= link_to "Products", '/products'  %></li>
		<li><%= link_to "Archive",  archive_path %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="stick_on: large">
  
    <section class="top-bar-section">
      <ul class="title-area">
        <li class="name">
          <%= link_to image_tag("jandj.png", alt: "J and J Capitol Enterprises"), root_path, id: "logo" %>
        </li>
      </ul>
      <ul class="right">
        <li class="active"><%= link_to "Home",     root_path    %></li>
        <li><%= link_to "Products", '/products'  %></li>
        <li><%= link_to "Archive",  archive_path %></li>
      </ul>
    </section>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/archive.html.erb
<% provide(:title, "Archive") %>

app/views/static_pages/home.html.erb
<div class="row">
	<div class="small-11 small-centered columns">
		<div class="panel">
			<h4 class="highlight">Quality</h4>
			<hr class="highlight">
			<p>For over 70 years, Bardahl has produced high quality products for the automotive market. Under strict guidelines of their Quality Assurance Program, they continue to be one of the most respected and trusted names in the market place worldwide. From formulation to production, Bardahl uses advanced technology in Quality Control to ensure the consumer receives the highest quality product.</p>
			<div class="row">
				<div class="small-4 columns text-center">
					<h6 class="highlight">Fuel Additives</h6>
					<img src="/assets/fuel.png" alt="Fuel Additives">
				</div>
				<div class="small-4 columns text-center">
					<h6 class="highlight">Oil Additives</h6>
					<img src="/assets/oil.png" alt="Oil Additives">
				</div>
				<div class="small-4 columns text-center">
					<h6 class="highlight">Motor Oil</h6>
					<img src="/assets/motoroil.png" alt="Motor Oil">
				</div>
			</div>
		</div>

		
		<div class="panel">
			<h4 class="highlight">Bardahl In Action</h4>
			<hr>
			<div class="row">
				<div class="medium-6 columns">
					<div class="flex-video center">
						<iframe src="//www.youtube.com/embed/AA9iPhY-TZY" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
				<div class="medium-6 columns">
					<div class="flex-video center">
						<iframe src="//www.youtube.com/embed/dnYrSU9a3fg" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
		
		<div class="panel">
			<h4 class="highlight">The Secret of Bardahl's Success Since 1939: A Technical Innovation</h4>
			<hr>
			<p>
				In 1939 a Norwegian engineer Ole Bardahl developed a revolutionary lubrication principle, based on a polarization phenomenon. Prior to Bardahl, lubricants were weak, molecular-attraction based formulas that breakdown during uses. <span class="highlight">Bardahl’s polar attraction formula allows lubricants to maintain an anti-friction, anti-wear and extreme pressure</span> microscopic film insulating every moving metal part in any mechanical system. The product was and is still revolutionary that the American Army decided to keep it as a defense secret till the end of the War .Soon after the War concluded Bardahl was being sold internationally to the finest mechanics and auto enthusiasts. Bardahl delivers championship-level products and protection in every product.
			</p>
		
			<p>
				<h4 class="highlight">BARDAHL - A WINNING TRADITION FOR MORE THAN 65 YEARS</h4>
				<img src="/assets/boat.jpg" alt="The best use Bardahl" class="right boat-right">
				After 1939, racing enthusiast in America found that adding Bardahl to their automobiles gave them an advantage over there competition. These enthusiasts demanded performance and Bardahl delivered every time .Bardahl is present in all forms and levels of racing around the world including Formula 1, The Indy car Circuit (now Indy Racing League), Unlimited Hydroplanes, Airplanes, Off-Road and World Rally Championship Series and world famous races such as the Indianapolis 500, Monte Carlo and the Paris to Dakar. The best use Bardahl.
			</p>

			<p>	
				<h4 class="highlight">No Oil Run</h4>
				Bardahl is often tested in every day usage .The 
				most challenging and hardest on engines is the 
				demanding NO-Oil-RUN. This test consists of 
				adding Bardahl to an engine, letting it run for 
				only a few minutes, draining the oil out of the 
				engine completely and then driving a distance of 
				more than 1300 km about (900) +miles. At the end of the test, the engine is completely dismantled and inspected for wear and tear. Bardahl's proven technology protects engine even under these conditions. Completed in several countries including America, Malaysia, Argentina and most recently Italy in a large 18 wheel truck, this test proves Bardahl's long lasting protection of the most critical metal components found in an engine.
			</p>
		</div>
	</div>
</div>